### ISSUE TITLE
Web server data update in real time

### ISSUE THREAD

**Issue by ceeim** [Unicorndy/covid19_dashboard#1]
I use Heroku to deploy a bit slower, so it is deployed on my own server, but the data cannot be automatically updated. I can only get the latest data by restarting covid19.py. If I want to update automatically, how should it be implemented in Python? -- Python beginner

**Comment by Unicorndy** [comment]
You can try using callback, so everytime a specific task is call, the data
will be read again from source.

Alternatively, as Johns Hopkins University only update their Global Time Series data once a day, you can restart your script once a day which is similar to what heroku server is doing. As stated on Heroku website, this is to help maintain the health of applications running on Heroku.
