### ISSUE TITLE
Version 1.0 Dashboard Issue

### ISSUE THREAD

**Issue by NoctuG** [Unicorndy/covid19_dashboard#3]
Version 1.0 Dashboard can't show Global Outbreak Map ( following Screenshot )

[![Screenshot-20201128-125429.jpg](https://i.postimg.cc/j24jLBxw/Screenshot-20201128-125429.jpg)](https://postimg.cc/0Krv4WJP)

**Comment by Unicorndy** [comment]
Hi, It should be working now.
